### ISSUE TITLE
Can't run GZDoom 4.4.2-4.fc33 + 4.5.0-1.fc33

### ISSUE THREAD

**Issue by aboutafter** [nazunalika/rpmspecs-gzdoom#2]
After today's update to 4.4.2-4 I can't open GZDoom on Fedora 33. I get this error:

```
$ gzdoom
GZDoom <unknown version> -  - SDL version
Compiled on Oct 26 2020

M_LoadDefaults: Load system defaults.
gzdoom: /builddir/build/BUILD/gzdoom-g4.4.2/src/common/objects/dobject.h:253: PClass* DObject::GetClass() const: Assertion `Class != nullptr' failed.
Aborted (core dumped)
```

**Comment by aboutafter** [comment]
Same problem after today's update:

```
$ gzdoom 
GZDoom <unknown version> -  - SDL version
Compiled on Nov  4 2020

M_LoadDefaults: Load system defaults.
gzdoom: /builddir/build/BUILD/gzdoom-g4.5.0/src/common/objects/dobject.h:253: PClass* DObject::GetClass() const: Assertion `Class != nullptr' failed.
Aborted (core dumped)
```

**Comment by nazunalika** [comment]
Thank you for the report, and I apologize for not seeing this right away - Can you tell me what wads/pk3's you're using or trying to load, if any? Once I have that, I will see if I can reproduce the issue with both the RPM and with a manual build. This should help indicate if it's an issue with my build or if it's an issue with gzdoom/wads itself (kind of like [here](https://forum.zdoom.org/viewtopic.php?f=2&t=69788))

**Comment by aboutafter** [comment]
I use your copr on two different PC's and the problem exists in both (a desktop with an Nvidia card and a Thinkpad x230). It doesn't even load the WAD selection screen, so the WADs are not the problem. If I try running an specific WAD (even the original Doom or Doom 2) I got the same error though. 

Since I couldn't use your version, I've downloaded the original source code from Github and compiled/ran it without an issue. 

Thank you for looking at the issue!

**Comment by nazunalika** [comment]
I think I nailed down the issue - Can you please test `4.5.0-2` and see if it works for you?

![image](https://user-images.githubusercontent.com/11469736/98406412-27e60280-202b-11eb-8f76-049d959bcf83.png)

Self notes... I think it has something to do with Fedora's %make_build macro. I also added debuginfo stuff back so that next time, we should be able to debug it that way without having to make a manual build.

**Comment by aboutafter** [comment]
It seems fixed, thank you! and thank you for you work with this repo, it makes running an up to date GZDoom a breeze.

**Comment by nazunalika** [comment]
Glad to hear it, don't hesitate to open another issue if something else comes up. Thank you for the report!
