### ISSUE TITLE
Start building for Fedora 34?

### ISSUE THREAD

**Issue by aboutafter** [nazunalika/rpmspecs-gzdoom#3]
Hello again, 

I hope I'm not bothering you too much. 

I just wanted to know if you plan on adding support for Fedora 34 on your copr. I've updated a couple of PC's to it and DNF was complaining about missing URL. It's just that your repo has become a must have on all my PC's and it would be nice to have it up a running when the final F34 is released. 

Thank you! and have a nice day.

**Comment by nazunalika** [comment]
Hello. I didn't receive a notification for this, so I apologize for the late response.

https://copr.fedorainfracloud.org/coprs/nalika/gzdoom/build/2108585/ - As of this writing, it's currently building. It might finish sooner than I expect. Once it's all done, dnf should then see the repos and you may receive an update (`.f33` -> `.f34`).

After some thought, I realize that adding any beta as a target in copr doesn't actually hurt. I've generally not done that, but I think down the road I'll try to do that and keep that consistent, so users like yourself won't run into that again.

**Comment by aboutafter** [comment]
Already updated and working perfectly.

Thank you very much! you are the best!
