### ISSUE TITLE
Missing gzdoom.pk3

### ISSUE THREAD

**Issue by pizzadude** [nazunalika/rpmspecs-gzdoom#4]
**Below, describe the bug**
The latest version in your repo (4.8.0-2.fc36.x86_64) still has the missing gzdoom.pk3 error, but if I "cd /usr/share/doom" and then launch gzdoom, it launches. But this is not ideal.

**Fedora Version + Archictecture**
 - Fedora: 36 (KDE)
 - Arch: x86_64

**Comment by nazunalika** [comment]
Thank you for the report. Yes, it's unfortunately still broken. I'm trying to sort out a workaround or a fix to this and hopefully get something pushed out soon. The devs haven't responded [here](https://github.com/coelckers/gzdoom/issues/1615) yet.

I'm sorry for the inconvenience!

**Comment by pizzadude** [comment]
It's okay, for now I'm using the gzdoom flatpak with a custom alias script. Thanks for maintaining this copr over the years!

**Comment by remyabel2** [comment]
See my comment here: https://github.com/coelckers/gzdoom/issues/1615#issuecomment-1148619217

**Comment by remyabel2** [comment]
For now, a potential workaround is to revert commit https://github.com/coelckers/gzdoom/commit/010f41a3aad3719b1e5d4d8ce157a5d9b0077b44. I didn't notice any glaring issues when doing this.

**Comment by nazunalika** [comment]
There is an update in the copr coming in that should address this issue for now.

**Comment by pizzadude** [comment]
It works now, thanks! Should I close this issue?

**Comment by nazunalika** [comment]
I think we can close this issue. Thank you for the report! I hope the devs will take a look at it and get a fix in for 4.8.1 soon.
