### ISSUE TITLE
[REF] Exclude .build-id folder from the RPMs

### ISSUE THREAD

**Issue by runlevel5** [nazunalika/rpmspecs-gzdoom#6]
The `.build-id` should not be included in the RPM packages.

```
tle@shrimp-paste:~/Work/rpmspecs_multimc$  rpm -qlp /home/tle/rpmbuild/RPMS/ppc64le/gzdoom-4.10.0-5.fc39.ppc64le.rpm 
...
/usr/lib/.build-id
/usr/lib/.build-id/8c
/usr/lib/.build-id/8c/d022fd68b96b0b2ef18139e2d1f42635b08390
...
tle@shrimp-paste:~/Work/rpmspecs_multimc$  rpm -qlp /home/tle/rpmbuild/RPMS/ppc64le/gzdoom-debuginfo-4.10.0-5.fc39.ppc64le.rpm 
...
/usr/lib/debug/.build-id
/usr/lib/debug/.build-id/8c
/usr/lib/debug/.build-id/8c/d022fd68b96b0b2ef18139e2d1f42635b08390
/usr/lib/debug/.build-id/8c/d022fd68b96b0b2ef18139e2d1f42635b08390.debug
...
```

**Comment by nazunalika** [comment]
Thank you for the RFE.

It is normal for these to appear in RPM builds for Fedora and Enterprise Linux 8+ under normal circumstances. See [here](https://fedoraproject.org/wiki/Releases/FeatureBuildId) and [here](https://fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo).

```
[label@sani ~]$ rpm -q gnome-desktop4 -l | grep build-id
/usr/lib/.build-id
/usr/lib/.build-id/86
/usr/lib/.build-id/86/14c2c1863b8cf71beab126602e21a2d7895222
/usr/lib/.build-id/d5
/usr/lib/.build-id/d5/12b65815cc80ae8017394c74fe76855668d400
/usr/lib/.build-id/e6
/usr/lib/.build-id/e6/e01be1b127198c8c70b7c19ce5c6e7acfc20b8
```

Could you please detail why build-id should be removed? What is the technical net benefit of removing these?

**Comment by runlevel5** [comment]
@nazunalika great thanks for pointing out that doc. It is totally my misunderstanding of its usage as I was having impression it was being generated as unneeded build artefacts.
